apiVersion: apps/v1
kind: Deployment
metadata:
  name: surgeon
spec:
  replicas: 2  # HPA takes over from here
  template:
    spec:
      containers:
        - name: surgeon
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 4
              memory: 4Gi
