#!/usr/bin/env bash
# scripts/setup.sh — one-time setup wizard.
#
# Walks through:
#  - GitHub App creation (manifest flow)
#  - Capturing App ID, private key, webhook secret
#  - Smee.io channel for webhook tunneling
#  - Anthropic + OpenAI API keys
#  - Optional: forking 1-2 OSS repos to your personal account as demo targets
#  - Creating .env.local
#
# After this completes, run: ./scripts/dev.sh

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

echo ""
echo "=============================="
echo "  Repo Surgeon — Setup Wizard "
echo "=============================="
echo ""

# Step 1: gh CLI
if ! command -v gh >/dev/null 2>&1; then
  echo "❌ gh CLI not installed. Install from https://cli.github.com/ and re-run."
  exit 1
fi
if ! gh auth status >/dev/null 2>&1; then
  echo "❌ gh CLI not authenticated. Run 'gh auth login' and re-run."
  exit 1
fi
GH_USER=$(gh api user --jq .login)
echo "✓ Logged in to GitHub as: $GH_USER"
echo ""

# Step 2: API keys
echo "▶ LLM API keys"
if [ -z "${ANTHROPIC_API_KEY:-}" ]; then
  read -rsp "  ANTHROPIC_API_KEY: " ANTHROPIC_API_KEY
  echo ""
fi
if [ -z "${OPENAI_API_KEY:-}" ]; then
  read -rsp "  OPENAI_API_KEY (or press Enter to skip): " OPENAI_API_KEY
  echo ""
fi

# Step 3: smee.io channel
echo ""
echo "▶ Webhook tunnel (smee.io)"
echo "  Open https://smee.io/new in your browser, click 'Start a new channel',"
echo "  and paste the URL here:"
read -rp "  SMEE_URL: " SMEE_URL

# Step 4: GitHub App creation
echo ""
echo "▶ GitHub App creation"
echo "  We'll open the GitHub App creation page in your browser."
echo "  Set the webhook URL to: $SMEE_URL"
echo "  Permissions needed: Issues R/W, Pull requests R/W, Contents R/W, Metadata R, Checks R/W"
echo "  Events: issues, issue_comment, pull_request, push, installation"
echo ""
read -rp "  Press Enter when ready to open the page (manual creation, not manifest flow)..."
open "https://github.com/settings/apps/new" 2>/dev/null || true

echo ""
echo "  After creating the App, you'll see App ID and a button to generate a private key."
read -rp "  GITHUB_APP_ID: " GITHUB_APP_ID
read -rsp "  GITHUB_WEBHOOK_SECRET (set this in App settings; paste it here): " GITHUB_WEBHOOK_SECRET
echo ""
echo "  Download the App's private key as a .pem file. Move it to:"
echo "    $ROOT/secrets/github-app-private-key.pem"
read -rp "  Press Enter when the .pem is in place..."

# Step 5: Demo target repos
echo ""
echo "▶ Demo target repos (optional)"
read -rp "  Fork 1-2 small OSS repos as demo targets? [y/N]: " FORK_CHOICE
if [[ "$FORK_CHOICE" =~ ^[Yy]$ ]]; then
  while true; do
    read -rp "  Repo to fork (e.g. 'owner/repo'), or empty to stop: " FORK_REPO
    [ -z "$FORK_REPO" ] && break
    gh repo fork "$FORK_REPO" --clone=false || echo "  (already forked or failed)"
    NEW_REPO="$GH_USER/${FORK_REPO##*/}"
    gh api "repos/$NEW_REPO" -X PATCH -f has_issues=true >/dev/null || true
    gh label create "surgeon:fix" --repo "$NEW_REPO" --color "d73a4a" 2>/dev/null || true
    gh label create "surgeon:feature" --repo "$NEW_REPO" --color "a2eeef" 2>/dev/null || true
    gh label create "surgeon:refactor" --repo "$NEW_REPO" --color "0075ca" 2>/dev/null || true
    echo "  ✓ Forked $FORK_REPO → $NEW_REPO with surgeon labels"
  done
fi

# Step 6: Write .env.local
echo ""
echo "▶ Writing .env.local..."
cat > .env.local <<EOF
# Generated by scripts/setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY
OPENAI_API_KEY=$OPENAI_API_KEY

GITHUB_APP_ID=$GITHUB_APP_ID
GITHUB_APP_PRIVATE_KEY_PATH=./secrets/github-app-private-key.pem
GITHUB_WEBHOOK_SECRET=$GITHUB_WEBHOOK_SECRET

SMEE_URL=$SMEE_URL

DATABASE_URL=postgresql+asyncpg://surgeon:dev@localhost:5432/surgeon
REDIS_URL=redis://localhost:6379/0

AGENT_REPO_PATH=./repo-surgeon
WORKSPACE_ROOT=/tmp/surgeon-workspace
LOG_ROOT=./logs

DEFAULT_MODEL=anthropic:claude-opus-4-7
FALLBACK_MODEL=openai:gpt-5.1

MAX_COST_USD_PER_RUN=2.0
MAX_DURATION_S_PER_RUN=1800
MAX_PRS_PER_REPO_PER_DAY=5
EOF
echo "  ✓ .env.local written"

# Step 7: Install the App on chosen repos
echo ""
echo "▶ Final step: install the GitHub App on your repos"
echo "  Visit: https://github.com/settings/installations"
echo "  Click 'Configure' next to your app and select the repos to enable."
echo ""

echo "============================================"
echo "  Setup complete. Next: run ./scripts/dev.sh"
echo "============================================"
